apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwexample
spec:
  selector:
    matchLabels:
      app: dwexample
  template:
    metadata:
      labels:
        app: dwexample
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: rajeevzerok/dropwizardexample-service:latest
        imagePullPolicy: Always
        command: ["echo","abc"]
        args: ["HOSTNAME", "KUBERNETES_PORT"]
        ports:
        - containerPort: 8443
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 400Mi
