---
apiVersion: v1
kind: Namespace
metadata:
  name: zerok-injector

---
apiVersion: v1
kind: Service
metadata:
  namespace: zerok-injector
  name: zerok-injector
  labels:
    app: zerok-injector
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
      name: webhook
    - port: 8444
      targetPort: 8444
      name: sync
  selector:
    app: zerok-injector

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: zerok-injector
  namespace: zerok-injector
  labels:
    app: zerok-injector

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerok-injector
  namespace: zerok-injector
  labels:
    app: zerok-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerok-injector
  template:
    metadata:
      name: zerok-injector
      labels:
        app: zerok-injector
    spec:
      serviceAccountName: zerok-injector
      containers:
        - name: zerok-injector
          image: us-west1-docker.pkg.dev/zerok-dev/stage/zerok-injector:test
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zerok-injector
  labels:
    app: zerok-injector
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
- apiGroups: ["v1",""]
  resources: ["secrets"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
- apiGroups: ["v1",""]
  resources: ["pods"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zerok-injector
  labels:
    app: zerok-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zerok-injector
subjects:
- kind: ServiceAccount
  name: zerok-injector
  namespace: zerok-injector