redis:
  host: localhost
  port: 6379
  readTimeout: 20
  pollingInterval: 30 #seconds

webhook:
  namespace: zerok-injector
  service: zerok-injector
  name: zerok-webhook
  path: /zk-injector
  port: 8443

logs:
  color: true
  level: DEBUG

debug: true
