redis:
  host: localhost
  port: 6379
  readTimeout: 20

webhook:
  namespace: zerok-injector
  service: zerok-injector
  name: zerok-webhook
  path: /zk-injector

server:
  port: 80

logs:
  color: true
  level: DEBUG

debug: true
